---
services:
  code-server:
    image: code-server-java:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
#      - PASSWORD=password #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.services.dystrophy.homelab.local
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /root/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  
